spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=${AZURE_KEY_VAULT_ENDPOINT}
spring.datasource.url=${datasource-url}
spring.datasource.username=${datasource-username}
spring.datasource.password=${datasource-password}

spring.jpa.hibernate.ddl-auto=none
