spring.profiles.active=dev
spring.web.resources.add-mappings=true
api.endpoint.base-url=/api/v1
server.port=80
management.endpoints.web.exposure.include=health,info,metrics,env,beans,configprops,heapdump,httpexchanges,loggers,mappings,custom-beans
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always
management.info.build.enabled=true
management.observations.annotations.enabled=true
management.info.env.enabled=true
management.info.git.enabled=true
management.info.git.mode=full
management.info.java.enabled=true
management.info.os.enabled=true
info.app.name=hogwarts-artifacts-online
info.app.description=Hogwarts Artifacts Online API
info.app.version=@project.version@
info.app.author=Mounika K